
services:
  # Blue Service (New version)
  users_blue:
    image: lmsusers:latest
    container_name: users_in_lms_network_blue
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: instance1,bootstrap
    networks:
      - lms_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 3
      timeout: 5s

  # Green Service (Old version)
  users_green:
    image: lmsusers:latest
    container_name: users_in_lms_network_green
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8085:8080" # Use a different port or set up a load balancer to direct traffic
    environment:
      SPRING_PROFILES_ACTIVE: instance2,bootstrap
    networks:
      - lms_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 3
      timeout: 5s

networks:
  lms_network:
    external: true

volumes:
  postgres_volume: